name: Manual and Push Workflow

on:
  workflow_dispatch:  # 這會添加手動觸發按鈕

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo Hello, this workflow was triggered by a ${{ github.event_name }} event.

      - name: Run multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.