name: manual test after merge stage

on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage

jobs:
  call_shared:
    if: github.ref == 'refs/heads/stage'
    uses: ./.github/workflows/shared_tests.yml