name: Manual Test After Merge Stage02

on:
  push:
    branches:
      - stage  # 只在 stage 分支推送時觸發
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - main
          - develop

jobs:
  call_shared:
    runs-on: ubuntu-latest
      - name: Run shared workflow
        uses: ./.github/workflows/tests.yml