name: Manual and Push Workflow00004

on:
  push:
    branches:
      - '*'  # 這會匹配所有分支
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.branch == 'stage'
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo Hello, this workflow was triggered by a ${{ github.event_name }} event.

      - name: Run multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.