name: manual test after merge stage02
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage

jobs:
  call:
    if: github.ref == 'refs/heads/stage'
    uses: ./.github/workflows/tests.yml
