name: Manual Test After Merge Stage02

on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'stage'
        type: 'choice'
        options:
          - stage
          - main
          - develop

jobs:
  call_shared:
    uses: ./.github/workflows/tests.yml
    with:
      branch: ${{ github.event.inputs.branch || 'stage' }}