name: only run in stage develop03
on:
  push:
    branches-ignore:
      - stage
jobs:
  int_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: int_test
        run: echo "Running integration tests"

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: unit_test
        run: echo "Running unit tests"