name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'         # 匹配所有分支
      - '!master'   # 排除 master 分支
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run tests'
        required: true
        default: true
        type: boolean

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && github.ref != 'refs/heads/master') ||
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: echo "Building the project"
      
      - name: Run tests
        if: |
          (github.event_name == 'push') ||
          (github.event_name == 'workflow_dispatch' && inputs.run_tests)
        run: echo "Running tests"

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy
        run: echo "Deploying the project"