name: only run in stage develop
on:
  push:
    branches-ignore:
      - stage

jobs:
  int_test:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/stage')
    steps:
      - uses: actions/checkout@v2
      - name: int_test
        run: echo "Running integration tests"

  unit_test:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/stage')
    steps:
      - name: unit_test
        run: echo "Running unit tests"